[package]
name = "letcom"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursive = "0.20.0"
dotenv = "0.15.0"
lettre = "0.10.1"
